title: Alex Carpenter
url: "http://alexcarpenter.me"

# Gems
gems:
  - jekyll-gist
  - jemoji
  - jekyll-seo-tag

# Collections
collections:
  pages:
    output: true
    permalink: :path

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - ./assets/js/app.js