title: Alex Carpenter
url: "http://alexcarpenter.me"
gems:
  - jemoji
  - jekyll-seo-tag
sass:
  sass_dir: _assets/stylesheets
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - webpack.config.js
