title: Alex Carpenter
description: >
  I'm a front-end developer focused on performance and accessibility.
email: im.alexcarpenter@gmail.com
timezone: America/Detroit
location: Grand Rapids, MI
baseurl: ""
url: "https://alexcarpenter.me"

# Directory tweaks
source: src/jekyll
destination: dist
permalink: pretty

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

# Files/folders
include: [_indexes]
keep_files: [assets]

# SEO
twitter:
  username: hybrid_alex
author:
  twitter: hybrid_alex
social:
  name: Alex Carpenter
  links:
    - https://twitter.com/hybrid_alex
    - https://www.linkedin.com/in/imalexcarpenter
    - https://github.com/alexcarpenter

# Collections
collections:
  links:
    output: true

# Defaults
defaults:
  - scope:
      type: posts
    values:
      layout: post

# Pagination
# pagination:
#   enabled: true
#   title: ':title'
#   permalink: '/:num'
#   sort_reverse: true
#   per_page: 10
