title: Alex Carpenter
description: >
  I'm a front-end developer focused on performance and accessibility.
email: im.alexcarpenter@gmail.com
location: Grand Rapids, MI
baseurl: ""
url: "https://alexcarpenter.me"
# Directory tweaks
source: src/jekyll
destination: dist
# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
# Keep static files
keep_files:
  - assets
  - CNAME
  - favicon.ico
  - humans.txt
  - manifest.json
  - robots.txt
  - service-worker.js
# SEO
twitter:
  username: hybrid_alex
author:
  twitter: hybrid_alex
social:
  name: Alex Carpenter
  links:
    - https://twitter.com/hybrid_alex
    - https://www.linkedin.com/in/imalexcarpenter
    - https://github.com/alexcarpenter
